# This is a basic workflow to help you get started with Actions

name: Demo

# Controls when the workflow will run
on:
   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   main:
      uses: shrikantrshelke/shared-workflow/.github/workflows/main.yml@main
     
  #build:
  #   needs: [parse]
  #   uses: shrikantrshelke/shared-workflow/.github/workflows/build.yml@main
