# This is a basic workflow to help you get started with Actions

name: main

# Controls when the workflow will run
on:
   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hoist:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Parsing pipeline.yml
        uses: mikefarah/yq@v4.30.6
        with:
          cmd: wf_list=$(yq e '.pipeline[].wf' infa/pipeline.yml)
